# Generated by Django 4.2.2 on 2023-08-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.AddField(
            model_name='order',
            name='tray_item',
            field=models.ManyToManyField(to='main.trayitem'),
        ),
    ]
